name: Python CI
run-name: ${{ github.actor }} checking if Weekly Check files are working
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential gcc
    - name: Install packages
      run: make install
    - name: Format
      run: make format
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Git
      run: make git
    - name: Save to repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo GH_TOKEN: "${GH_TOKEN}"
        git config --global user.name 'github-actions'
        git config --local user.email "action@github.com"
        git add .
        git commit -m "Adding Files" || echo "ignoring commit errors"
        git push
